# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zig-0.0.0-Fp4XJAKeOAtV1Beb0V7RbMSVXxgQ19_X2qXe6J650kkt";
    path = fetchzip {
      url = "https://github.com/ziglang/zig/archive/03123916e55a9c0c8b66f748a62b7a4a64203535.tar.gz";
      hash = "sha256-wFnSQR755pZgOEKDgCey6RK/0mGqR8U4D4bZhqmSrxE=";
    };
  }
]
