name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, macos-13, ubuntu-24.04-arm]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Run tests
        run: zig build test

      - name: Run executable
        run: |
          git clone https://github.com/zigtools/zls
          nix run .#default_0_13 -- zls
          nix run .#default_0_14 -- zls
          nix run . -- zls
          git clone https://git.sr.ht/~leon_plickat/wayprompt
          nix run .#default_0_13 -- wayprompt
          nix run .#default_0_14 -- wayprompt
          nix run . -- wayprompt

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Check formatting
        run: zig fmt --check .
